version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.72.0
    volumes:
      - ./otel-config.yml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    ports:
      - "4317:4317"